### ISSUE TITLE
[Feat] 찜 화면 기본 UI 구현

### ISSUE THREAD

**Issue by nolanMinsung** [NOW-SOPT-APP1-YeogiEottae/YeogiEottae-iOS#11]
## 🛠 Issue

찜 화면(가칭 FavoritesView) 기본 UI 화면 구현

## 📝 To-do

- [ ] navigation bar 위치에 커스텀 세그먼트 컨트롤 구현하기(stackView 이용 예정)
- [ ] 기본 컬렉션 뷰 UI 구현하기(스와이프 인터렉션 기능은 새 이슈 팔 예정)
- [ ] 비교하기 버튼을 누를 시 CompareRoomView가 push되도록 구현
