### ISSUE TITLE
[Feat] HotelDetailVC의 기본 구조 수정

### ISSUE THREAD

**Issue by codeJiwon** [NOW-SOPT-APP1-YeogiEottae/YeogiEottae-iOS#13]
## 🛠 Issue

tableview로 복잡한 UI를 구현하려다 보니 전체 tableview에 대한 레이아웃은 설정했으나, 그 안에 때려넣은 셀의 레이아웃을 설정하기 어려워짐. 
코드로 레이아웃을 잡는 게 아니라 그냥 셀을 붙이는 식으로 야매로 구현해야 하는 상황…따라서 collectionView로 바꿔야함.
## 📝 To-do

- [ ] UIImageView를 컬렉션뷰로 구현하고(b/c 가로 스크롤)
- [ ] 밑에 호텔 이름은 UIView로 구현
- [ ] 그 밑은 compositional 컬렉션 뷰로 구현
