### ISSUE TITLE
[Feat] RoomDetailView UI 구현

### ISSUE THREAD

**Issue by codeJiwon** [NOW-SOPT-APP1-YeogiEottae/YeogiEottae-iOS#35]
## 📝 To-do

- [x] 섹션 3개로 나눔
- [x] 이미지 섹션 UI 구현
- [x] 인포 섹션 UI 구현
- [x] 상세설명 섹션 UI 구현
