### ISSUE TITLE
[Feat] HotelDetailVC UI 기본구조

### ISSUE THREAD

**Issue by codeJiwon** [NOW-SOPT-APP1-YeogiEottae/YeogiEottae-iOS#5]
## 🛠 Issue

전체를 tableview로 구현하고, 3개의 section으로 나눔.
첫번째 섹션은 호텔 사진 UIImageView를 포함하고, 두번째 섹션은 호텔의 detail 내용으로 2개의 셀이 존재한다.
세번째 섹션은 호텔의 room이 나타나는데, 2개의 셀이 존재한다.
## 📝 To-do

- [x] 전체 구조 색으로 표현
- [x] 투명한 네비게이션 바 붙이기
- [ ] 섹션 레이아웃 설정
