### ISSUE TITLE
[Feat] SearchListView 상단 세그먼트 컨트롤러 및 좌우 스크롤 구현

### ISSUE THREAD

**Issue by nolanMinsung** [NOW-SOPT-APP1-YeogiEottae/YeogiEottae-iOS#8]
## 🛠 Issue

SearchListView의 좌우 스크롤과 이에 따른 상단 세그먼트 컨틀롤러(커스텀) 구현하기

## 📝 To-do

- [x] pageVC로 구현
- [x] 상단 세그먼트 컨트롤러 기존 UIScrollView -> UICollectionView로 변경하기
- [x] 세그먼트 컨트롤러의 underBar 애니메이션 구현하기

## 🛠️수정할 사항
- [ ] pageVC의 좌우 스크를 시 underBar는 움직이지만, segment control의 폰트는 변하지 않는 현상 해결하기
- [ ] 상하 스크롤 시, 상단의 날짜, 옵션, 세그먼트 컨트롤이 사라지고 네비게이션 바가 바뀌는 기능 구현하기
